### ISSUE TITLE
Version 0.1 Alpha: test report

### ISSUE THREAD

**Issue by ghost** [scemino/NScumm.Audio#1]
Hi

I tested Version 0.1 Alpha on windows 10 using the 2 files attached. The file plays correctly using a player that has AdPlug (audacious and foobar2000).

- DRO file captured using DOSBox 0.74-3:

test.dro: the player does not write anything to the screen and no sound is heard. 

- IMF file downloaded from http://www.shikadi.net/wiki/files/keenmusic-r3.zip

test.imf: System.DllNotFoundException while openal is installed and openal32.dll is copied to EXE folder

NScumm.Audio.ALPlayer test.imf

Unhandled exception. System.DllNotFoundException: Unable to load DLL '/System/Library/Frameworks/OpenAL.framework/OpenAL' or one of its dependencies (0x8007007E)
   at OpenAL.Alc.OpenDevice(String deviceName)
   at NScumm.Audio.AlPlayer.AlPlayer..ctor(IMusicPlayer player, Int32 rate) in /home/runner/work/NScumm.Audio/NScumm.Audio/NScumm.Audio.Player/AlPlayer.cs:line 46
   at NScumm.Audio.AlPlayer.Program.Main(String[] args) in /home/runner/work/NScumm.Audio/NScumm.Audio/NScumm.Audio.Player/Program.cs:line 51

[files.zip](https://github.com/scemino/NScumm.Audio/files/4933399/files.zip)

**Comment by scemino** [comment]
Yes as you emailed me, it seems like the OpenAL nuget does not support Windows yet.

**Comment by ghost** [comment]
After contacting the developer of openAL.NetCore, an update is on nuget now.
I'll test it in the current code by updating my nuget package.

**Comment by ghost** [comment]
After setting the project to .NET Core 3.1 which OpenAL.NetCore's minimum supported version is and installing OpenAL.NetCore 1.0.2, rebuilding everything, I still get this error:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenAL.Al' threw an exception.
  Source=OpenAL.NETCore
  StackTrace:
   at OpenAL.Al.GenSources(Int32 n, UInt32[]& sources)
   at NScumm.Audio.AlPlayer.AlPlayer.AudioPlayerThread() in F:\Visual Studio project\NScumm.Audio-master\NScumm.Audio.Player\AlPlayer.cs:line 108
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.NativeLibrary.SetDllImportResolver(System.Reflection.Assembly, System.Runtime.InteropServices.DllImportResolver)
    OpenAL.Al.Al()

Inner Exception 1:
InvalidOperationException: A resolver is already set for the assembly.

**Comment by ghost** [comment]
Attached a screenshot with exception details for the OpenAL.NetCore developer. 
This exception occurs in Windows 10, Visual studio 2019 community with OpenAL installed in C:\Windows\System32 and in the EXE's folder. The code is build using .Net Core 3.1

![exception](https://user-images.githubusercontent.com/65877513/87789070-b34e4480-c83e-11ea-942d-3622ad4347ec.jpg)

**Comment by scemino** [comment]
It seems still a bug in the openal library, did you contact the author for this issue?

**Comment by scemino** [comment]
It seems still a bug in the openal library, did you contact the author for this issue?

**Comment by scemino** [comment]
It has been fixed by this commit e5770a1565e96056009b9dbb6a6f4d6e1be4236f
